### ISSUE TITLE
bounds checking?

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/ndio-demos#4]
```
Traceback (most recent call last):
  File "forforrest.py", line 11, in <module>
    aratome_vol = oo.get_cutout('Aratome15d_S05_W01', 'rb_anti_synapsin', 10000, 1100, 0, 4421, 0, 4, resolution=0)
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 310, in get_cutout
    z_start, z_stop)
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 368, in _get_cutout_no_chunking
    raise IOError("Bad server response: {}".format(req.status_code))
IOError: Bad server response: 404
```

Might not be a bad idea to check that upper bound > lower bound and provide a more descriptive error message. @willgray thoughts?

Edit: way to put this in ndio-demos, Alex. :-1:

**Comment by j6k4m8** [comment]
good point — adding it to my todo in _the ndio repository where it belongs_

**Comment by Aeusman** [comment]
Closing this in favor of ndio issue.
